# Generated by Django 3.2.15 on 2022-10-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contacto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Familiar',
        ),
    ]
