# Generated by Django 3.2.15 on 2022-10-17 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_contacto_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='email',
        ),
    ]
